- name: Install VIM
  ansible.builtin.apt:
    name: "vim"
    state: present

- name: Setup the directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: '0755'
  loop: 
    - "{{ home }}/.vim"
    - "{{ home }}/.vim/autoload"

- name: Install the VIM Plugin Manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.vim/autoload/plug.vim"

- name: Copy the VIM config
  copy:
    src: vimrc
    dest: "{{home}}/.vimrc"
